title: ЗНАЙ-НАЙ
description:
  Курсове по математика за кандидат-гимназисти, които включват индивидуални
  занимания и представят учебния материал по лесен и достъпен начин без стреса
  на училищната обстановка.
google_analytics:
  UA-102978713-1
collections:
  pages:
    output: true
    permalink: /:name

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sign_form_link: https://goo.gl/forms/kxwWFMP1rajArPHv1
